services:
  - type: web
    name: zyvo-creator
    runtime: node
    plan: free

    buildCommand: npm install

    startCommand: npm start

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: PLATFORM_URL
        sync: false
